### PR TITLE
Dbus cli calls

### PR DESCRIPTION
**Pull request by dmytrovoytko**
Thank you for this app - simple and really helpful!

@collinss Please consider adding DBUS calls as a solution to #3

### CODE REVIEW

**Comment by claudiux** [comment]
@collinss @clefebvre Seems to work well.

**Comment by dmytrovoytko** [comment]
I know the team was busy with LMDE6, thank you very much for your great work!
Any feedback/updates on this PR?

**Comment by claudiux** [comment]
@dmytrovoytko
.@collinss is working on a new version of sticky: https://github.com/linuxmint/sticky/pull/115

**Comment by collinss** [comment]
@dmytrovoytko thanks for your contribution! In the end, I decided to go a slightly different route (#115).

**Pull request closed without merging**
